### ISSUE TITLE
whats nebloid?

### ISSUE THREAD

**Issue by dec1** [NeblioTeam/docker-nebliod#2]
"Docker Containers for nebliod"
what is nebloid?

**Comment by TheQuantumPhysicist** [comment]
@dec1  It's the terminal version of neblio, without a graphical user interface. Commonly used by businesses and exchanges.

And please don't open issues on github for such questions. Github issues are reserved for technical bugs and similar. We're on discord and telegram and always answer people's questions.

**Comment by dec1** [comment]
Hello and thanks for the reply.

Id suggest it is a bug (in the documentation) as every github repo should start with a clear statement about what the project does.
Many "technical bugs and similar" issues seem to be ignored here in general (see eg [here](https://github.com/NeblioTeam/electrum-nebl/issues))
And several (technical) questions I posed on your other channels were met with answers along the lines of "our documentation will be improved soon. Please wait for that."
