### ISSUE TITLE
debug.log

### ISSUE THREAD

**Issue by jphellemons** [NeblioTeam/docker-nebliod#4]
I am running the docker image for a while now (on a raspberry pi4) and see a lot of 
```
CheckBlock() : block timestamp too far in the future
```
or `
```
ProcessBlock() : already have block 3010292
```

the first message does occur a lot. 

![image](https://user-images.githubusercontent.com/1119134/119543375-e29fdd00-bd90-11eb-8a12-c7a5a6646df7.png)

Is there something I can do to fix it?

**Comment by nebliodev** [comment]
`CheckBlock() : block timestamp too far in the future`

Will only be shown in the logs if the node is processing a block that has a timestamp 10 or more minutes in the future compared to your server's system time. Please ensure your servers system time is synced properly and the timezone is set correctly. (normally this is a timezone issue if you are seeing this often).

`ProcessBlock() : already have block 3010292`

This is not an error, but a simple log statement. These are completely normal. 

Closing this issue for now, but feel free to comment if you have further questions.

**Comment by jphellemons** [comment]
Thanks for the fast reply. I posted a screenshot of the system time of the docker host and of the docker container itself. It's all UTC. I am in GMT +2 due to the daylight saving, but by adding 2 hours to the utc does correspond to the actual time. So I have no idea what I need to do with the default neblio docker container.

**Comment by nebliodev** [comment]
All you should need to do is make sure the system time and timezone are set appropriately in Ubuntu (the host OS), preferably syncing with an NTP server, then restart the docker container.
